### ISSUE TITLE
Refactor to use of ES6 Classes 

### ISSUE THREAD

**Issue by mitogh** [Kikobeats/array-list#4]
I was wondering if you are open to a Refactor on this in order to use ES6 Classes to make it a little bit more familiar with Java I'm happy to open a PR if you want, just wanted to ask first.

Thank you.

**Comment by Kikobeats** [comment]
The problem with that is first compatibility with node versions and second, at this moment, ES6 optimization for v8 is too poor.

**Comment by mitogh** [comment]
Ok. 

I was planing to have just ES6 for development and deliver ES5 to the build as the entry point using Babel, so in that way the JS keeps being compatible with any browser.

**Comment by Kikobeats** [comment]
That's sounds cool, but honestly I think that you are investing effort, time and compilation time to be in the same starting point than now 😄

**Comment by mitogh** [comment]
Well I’m going to have some time waiting on the Airport ✈️,

Just wanted to know if you are open to this before start with this tomorrow.

Thanks :)

**Comment by Kikobeats** [comment]
thanks for read the code but not really!

so I'm going to contact with you to be part of other interesting projects that need people :)

**Comment by mitogh** [comment]
Sounds good thanks.
